prometheus-operator:
  enabled: true
  createCustomResource: false

global:
  nodeSelector:
    type: dependent_services

prometheus:
  prometheusSpec:
    retention: 7d
    
    nodeSelector:
      type: dependent_services
    
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}

grafana:
  enabled: true

  sidecar:
      datasources:
        defaultDatasourceEnabled: false  
  
  adminPassword: admin
  
  nodeSelector:
    type: dependent_services
  
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          isDefault: true
          access: proxy
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
          isDefault: false

  env:
    GF_FEATURE_TOGGLES_ENABLE: "disableKubernetesAPIServer"
    GF_DATABASE_MAX_IDLE_CONN: 10
    GF_DATABASE_MAX_OPEN_CONN: 100
    GF_DATABASE_CONN_MAX_LIFETIME: 14400

alertmanager:
  enabled: true

  alertmanagerSpec:
    nodeSelector:
      type: dependent_services

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    secrets:
      - alertmanager-slack-webhook

  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: slack
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: slack

    receivers:
      - name: slack
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack-webhook/slack-api-url
            channel: "#alerts"
            send_resolved: true
            title: '{{ .Status | toUpper }}: {{ .CommonAnnotations.summary }}'
            text: |-
              *Alert:* {{ .CommonLabels.alertname }}
              *Summary:* {{ .CommonAnnotations.summary }}
              *Description:* {{ .CommonAnnotations.description }}
              *Severity:* {{ .CommonLabels.severity }}
              *Status:* {{ .Status }}
              *Labels:* {{ .CommonLabels }}

prometheusOperator:
  nodeSelector:
    type: dependent_services

nodeExporter:
  enabled: true
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

kubeStateMetrics:
  enabled: true
  
  nodeSelector:
    type: dependent_services
  
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi