{
 "title": "API metrics",
 "time": { "from": "2026-03-11T10:39:05.001Z", "to": "2026-03-11T10:49:05.001Z" },
 "panels": [
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, endpoint, method) (\n    rate(http_request_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, endpoint, method) (\n    rate(http_request_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate percentage - 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 *\n(\n  sum by (method, endpoint) (\n    rate(http_requests_total{status=~\"4..\"}[5m])\n  )\n  /\n  sum by (method, endpoint) (\n    rate(http_requests_total[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate percentage - 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 *\n(\n  sum by (method, endpoint) (\n    rate(http_requests_total{status=~\"5..\"}[5m])\n  )\n  /\n  sum by (method, endpoint) (\n    rate(http_requests_total[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (\n  rate(http_requests_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}