{
 "title": "Application error logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({namespace=\"student-api\"} |= \"ERROR\" [5m]))"
    }
   ]
  },
  {
   "title": "Error log count (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({pod=~\"student-api-.*\"} |= \"ERROR\" [5m])"
    }
   ]
  },
  {
   "title": "Recent error logs(table)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"student-api\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "Errors by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (pod) (count_over_time({namespace=\"student-api\"} |~ `(?i)error` [5m]))"
    }
   ]
  }
 ]
}