{
 "title": "API checks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vault uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"vault-health\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"argocd-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{job=\"student-api-healthcheck\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}