{
 "title": "DB Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (usename) (\n  pg_stat_activity_count{backend_type=\"client backend\", datname=\"student_api\", state=\"active\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"student_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"student_api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"student_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Conns / Max Conns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"student_api\"}\n/\non(instance) pg_settings_max_connections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}