{
 "title": "Kube-state metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  rate(kube_pod_container_status_restarts_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (phase) (kube_pod_status_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready endpoints per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, endpointslice) (\n  kube_endpointslice_endpoints{ready=\"true\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas\n-\nkube_deployment_status_replicas_available",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Requests / Limits by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"})\n/\nsum by (namespace) (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests / Limits by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"})\n/\nsum by (namespace) (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}