apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default

  source:
    repoURL: https://github.com/sai29/one2n_sre_bootcamp.git
    targetRevision: main
    path: helm/observability/prometheus-rules

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false